version: "3.3"
services:
  app:
    image: ericfatec/desafio4:1.1
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientes
      MYSQL_USER: eric
      MYSQL_PASSWORD: eric
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

